export const enum REPOSITORIES {
  LoginRepository = 'LoginRepository',
  CartRepository = 'CartRepository',
  CommentCartRepository = 'CommentCartRepository',
  MultiCartRepository = 'MultiCartRepository',
  CheckoutAddressRepository = 'CheckoutAddressRepository',
  CheckoutCustomerRepository = 'CheckoutCustomerRepository',
  CheckoutShipmentRepository = 'CheckoutShipmentRepository',
  CheckoutPaymentRepository = 'CheckoutPaymentRepository',
  CheckoutSummaryRepository = 'CheckoutSummaryRepository',
  AgentLoginRepository = 'AgentLoginRepository',
  CatalogRepository = 'CatalogRepository',
  CompanyUserSelectRepository = 'CompanyUserSelectRepository',
  MerchantRelationRequestCreateRepository = 'MerchantRelationRequestCreateRepository',
  MerchantRelationRequestDetailsRepository = 'MerchantRelationRequestDetailsRepository',
  MerchantRelationRequestIndexRepository = 'MerchantRelationRequestIndexRepository',
  MerchantRepository = 'MerchantRepository',
}
