export const enum REPOSITORIES {
  YvesRepository = 'YvesRepository',
  HomeRepository = 'HomeRepository',
  LoginRepository = 'LoginRepository',
  CartRepository = 'CartRepository',
  CommentCartRepository = 'CommentCartRepository',
  MultiCartRepository = 'MultiCartRepository',
  CheckoutAddressRepository = 'CheckoutAddressRepository',
  CheckoutCustomerRepository = 'CheckoutCustomerRepository',
  CheckoutShipmentRepository = 'CheckoutShipmentRepository',
  CheckoutPaymentRepository = 'CheckoutPaymentRepository',
  CheckoutSummaryRepository = 'CheckoutSummaryRepository',
  AgentLoginRepository = 'AgentLoginRepository',
  CatalogRepository = 'CatalogRepository',
  ProductRepository = 'ProductRepository',
  CompanyUserSelectRepository = 'CompanyUserSelectRepository',
  MerchantRelationRequestCreateRepository = 'MerchantRelationRequestCreateRepository',
  MerchantRelationRequestDetailsRepository = 'MerchantRelationRequestDetailsRepository',
  MerchantRelationRequestIndexRepository = 'MerchantRelationRequestIndexRepository',
  MerchantRepository = 'MerchantRepository',
  CustomerOverviewRepository = 'CustomerOverviewRepository',
  ContentRepository = 'ContentRepository',
  ProductComparisonRepository = 'ProductComparisonRepository',
  OrderDetailsRepository = 'OrderDetailsRepository',
  ClaimRepository = 'ClaimRepository',
  CompanyRoleIndexRepository = 'CompanyRoleIndexRepository',
  CompanyRoleCreateRepository = 'CompanyRoleCreateRepository',
}
