#!/bin/bash

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    # Linux
    DISPLAY_IP=$(hostname -I | awk '{print $1}'):0
elif [[ "$OSTYPE" == "darwin"* ]]; then
    # Mac OSX
    DISPLAY_IP=$(ipconfig getifaddr en0):0
fi

if [[ "$SPRYKER_SSL_ENABLE" == "true" ]]; then
    SPRYKER_URL_PROTOCOL="https"
else
    SPRYKER_URL_PROTOCOL="http"
fi

ENV_BACKOFFICE_URL=${SPRYKER_URL_PROTOCOL}://${SPRYKER_BE_HOST}
ENV_MERCHANT_PORTAL_URL=${SPRYKER_URL_PROTOCOL}://${SPRYKER_MP_HOST}
ENV_MAIL_CATCHER_URL=${SPRYKER_URL_PROTOCOL}://${SPRYKER_SMTP_HOST}
OPERATION_RUNNER_URL=${SPRYKER_URL_PROTOCOL}://${SPRYKER_GLUE_BACKEND_HOST}/test-operation-runner
E2E_BASE_URL=${SPRYKER_URL_PROTOCOL}://${SPRYKER_FE_HOST}

export DISPLAY_IP=$DISPLAY_IP
export SPRYKER_URL_PROTOCOL=$SPRYKER_URL_PROTOCOL
export ENV_BACKOFFICE_URL=$ENV_BACKOFFICE_URL
export ENV_MERCHANT_PORTAL_URL=$ENV_MERCHANT_PORTAL_URL
export ENV_MAIL_CATCHER_URL=$ENV_MAIL_CATCHER_URL
export OPERATION_RUNNER_URL=$OPERATION_RUNNER_URL
export E2E_BASE_URL=$E2E_BASE_URL

exit 0
